# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: ManixChen
email: 18064266867@163.com
description: > # this means to ignore newlines until "baseurl:"
  专注于Web方向开发,让我们一起打开中国的IT大门，一起创造大家向往的It新纪元...
encoding: utf-8
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site
paginate: 4
paginate_path: "blog/page:num"
twitter_username: 陈明安
github_username:  ManixChen

# Build settings
markdown: kramdown
